version: '3'
services:

  airflowproject:
    image: airflow-project:latest
    environment:
      - AWS_ACCESS_KEY_ID=AKIA6GBMBRGXZIHIXL6W
      - AWS_SECRET_ACCESS_KEY=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
      - YOUTUBE_API_KEY=AIzaSyD1ZDOXbum9HiukOJgKNPn4O5jviRYk7yI
    volumes:
      - ./airflow:/opt/airflow
    ports:
      - "8080:8080"
    command: airflow standalone
    